### ISSUE TITLE
Inaccuracy about dam overtopping

### ISSUE THREAD

**Issue by WildUtah** [axibase/atsd-use-cases#18]
"The emergency spillway quickly began to erode and water began to spill over the top of the dam."

This never happened. The concrete emergency spillway elevation is 901'. The maximum elevation reached is just a few feet higher than that. But the main dam elevation is 922'. If water spilled over the top of the main earth-fill dam, it would be likely to collapse entirely creating a huge disaster.

http://www.water.ca.gov/swp/facilities/Oroville/LakeDam.cfm

**Comment by rodionos** [comment]
Thank you, text revised.
