### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Arthasasyan** [axibase/atsd-use-cases#461]
List of broken links:
1. https://github.com/axibase/docs-util/blob/master/docs/how-to-add-custom-linter-rule.md#how-to-add-custom-markdownlint-rule
at
[How to add costom markdownlint rules tutorial](https://github.com/axibase/atsd-use-cases/blob/master/tutorials/linter-tutorial/README.md#configuring-custom-rules)
This page does not exist. What should it be replaced with?
2. https://www.fresnobee.com/news/local/news-columns-blogs/earth-log/article19529637.html
at
[Last by one paragraph](https://github.com/axibase/atsd-use-cases/blob/master/tutorials/environmental-monitoring/README.md#collecting-and-streaming-data)
This page exists but is recognized as non-valid. Should it be added to [config](https://github.com/axibase/atsd/blob/master/.linkcheck-config.json) to be ignored?
3. https://duck.co/blog/post/176/-why-duckduckgo-is-giving-away-shirts
at
[DuckDuckGo Blog](https://github.com/axibase/atsd-use-cases/blob/master/chart-of-the-day/duck-duck-go/README.md#data-forecasting)
This link redirects to [web archive](https://web.archive.org/web/20180909180434/https://duck.co/blog/post/176/-why-duckduckgo-is-giving-away-shirts). Should it be added to [config](https://github.com/axibase/atsd/blob/master/.linkcheck-config.json) to be ignored?
4. https://vision2030.gov.sa/en/node/125
at
[Annotation 13](https://github.com/axibase/atsd-use-cases/blob/master/research/saudi-arabia/README.md#undisputed-legitimacy)
This page is forbidden for unauthorized users.
5. https://www.sacbee.com/news/business/article210466514.html
at
[Annotation 15](https://github.com/axibase/atsd-use-cases/blob/master/research/income-tax/README.md#controlling-californian-nonconformity) 
This page exists but is recognized as non-valid. Should it be added to [config](https://github.com/axibase/atsd/blob/master/.linkcheck-config.json) to be ignored?

**Comment by raipc** [comment]
@Arthasasyan Please, create PRs with fixes instead of issues.
Add domains to .linkcheck.config if the links are not working in travis (country- or useragent-restricted) but can be opened from browser. In case of 404 status code google for the article name and find new link or similar article from other news website
