### ISSUE TITLE
Divide by Purchasing power parity (PPP)

### ISSUE THREAD

**Issue by lpvm** [axibase/atsd-use-cases#84]
Great charts, thanks!

You could even improve it a bit.  To give even a better perspective, you could relate the debt per capita to the PPP of each country, as it's very different across Europe.

**Comment by kghamilton89** [comment]
Hello lpvm,
Thank you for reading and commenting. This is a great suggestion for an additional visualization. I've found the relevant data, will insert it into the database and release a follow-up to this article soon. 

Regards,
Ken

**Comment by lpvm** [comment]
Thanks!
